name: Update YouTube-Music Cask

on:
  schedule:
    # Run once every day at 3:15 AM UTC
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: macos-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v4

      - name: Update Cask File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CASK_FILE="Casks/youtube-music.rb"

          echo "Fetching latest release data for th-ch/youtube-music..."
          API_DATA=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/th-ch/youtube-music/releases/latest")
          
          LATEST_VERSION=$(echo "$API_DATA" | jq -r '.tag_name' | sed 's/^v//')
          # Use jq to find the download URL for the arm64 DMG
          DOWNLOAD_URL=$(echo "$API_DATA" | jq -r '.assets[] | select(.name | endswith("-arm64.dmg")) | .browser_download_url')
          
          if [ -z "$LATEST_VERSION" ] || [ "$LATEST_VERSION" = "null" ]; then
            echo "Error: Could not extract LATEST_VERSION from API."
            exit 1
          fi
          if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" = "null" ]; then
            echo "Error: Could not extract DOWNLOAD_URL for arm64 from API."
            exit 1
          fi

          CURRENT_VERSION=$(grep 'version "' "$CASK_FILE" | cut -d '"' -f 2)
          echo "Latest version is $LATEST_VERSION. Current version is $CURRENT_VERSION."

          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Cask is already up-to-date."
            exit 0
          fi
          
          echo "Downloading the new arm64 DMG..."
          curl -L -o new_cask.dmg "$DOWNLOAD_URL"
          NEW_SHA=$(shasum -a 256 new_cask.dmg | awk '{print $1}')
          
          if [ -z "$NEW_SHA" ]; then
            echo "Error: Could not calculate SHA256 sum."
            exit 1
          fi

          echo "New version found. Updating cask file..."
          echo "New SHA256 is $NEW_SHA"
          sed -i '' "s/version \"${CURRENT_VERSION}\"/version \"${LATEST_VERSION}\"/" "$CASK_FILE"
          sed -i '' "s/sha256 \".*\"/sha256 \"${NEW_SHA}\"/" "$CASK_FILE"
          echo "Cask file updated successfully."

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "$CASK_FILE"
          git commit -m "Update youtube-music cask to ${LATEST_VERSION}"
          git push
